import { FaHamburger } from "react-icons/fa";
export const navLinks = [
  { href: "#Home", label: "Home" },
  { href: "#About", label: "About" },
  { href: "#Menu", label: "Menu" },
  { href: "#Booking", label: "Booking" },
];

export const reviews = [
  {
    imageSrc: "/images/ks.webp",
    clientName: "John Doe",
    reviewText:
      "The food was absolutely wonderful, from preparation to presentation, very pleasing. We especially enjoyed the special bar drinks, the cucumber/cilantro infused vodka martini, and the coconut mojito.",
  },
  {
    imageSrc: "/images/ks.webp",
    clientName: "Jane Smith",
    reviewText:
      "Everything we ordered from the menu was delicious! The service was excellent and the staff were very friendly. A great dining experience overall. We will definitely be back!",
  },
  {
    imageSrc: "/images/ks.webp",
    clientName: "Michael Brown",
    reviewText:
      "The ambiance was perfect, and the vegetarian options were diverse and flavorful. It’s great to find a place that caters to vegetarian diets so well. Highly recommend!",
  },
];

export const foodItems = [
  {
    image: "/images/cheese.jpg",
    title: "Paneer Momos",
    price: 130,
    rating: 5.0,
    icon: "/images/momo2.jpg",
    category: "Momos",
  },
  {
    image: "/images/momo2.jpg",
    title: "Vegetable Momos",
    price: 100,
    rating: 3.8,
    category: "Momos",
  },
  {
    image: "/images/peri.webp",
    title: "Peri Peri Momos",
    price: 200,
    rating: 4.9,
    category: "Momo",
  },

  {
    image: "/images/noodles.jpg",
    title: "Malai Paneer Momos",
    price: 250,
    rating: 4.9,
    category: "Momos",
  },
  {
    image: "/images/fried.jpg",
    title: "Fried Momos",
    price: 160,
    rating: 4.9,
    category: "Momos",
  },
  {
    image: "/images/noodles.jpg",
    title: "Vegetable Noodles",
    price: 100,
    rating: 5.0,
  },
  { image: "/images/nod.jpg", title: "Haka Noodles", price: 160, rating: 4.8 },

  {
    image: "/images/mach.jpg",
    title: "Manchurian",
    price: 200,
    rating: 4.8,
    category: "Chinese",
  },
  {
    image: "/images/mach.jpg",
    title: "Cheese Chilli",
    price: 250,
    rating: 4.8,
    category: "Chinese",
  },
  {
    image: "/images/mach.jpg",
    title: "Mushroom Chilli",
    price: 250,
    rating: 4.8,
    category: "Chinese",
  },
  {
    image: "/images/cheese.jpg",
    title: "Mushroom Chilli",

    price: 16,
    rating: 4.8,
    category: "Chinese",
  },
  {
    image: "/images/fried.jpg",
    title: "Fried Rice",
    price: 160,
    rating: 4.8,
    category: "Chinese",
  },

  {
    image: "/images/noodles.jpg",
    title: "Garlic Noodles",
    price: 200,
    rating: 4.8,
    category: "Noodles",
  },
  {
    image: "/images/burger.jpg",
    title: "Aloo Tiki Burger",
    price: 170,
    rating: 4.8,
    category: "Burgers",
  },
  {
    image: "/images/decker.jpg",
    title: "Double Decker Burger",
    price: 250,
    rating: 4.8,
    category: "Burgers",
  },
  {
    image: "/images/burger3.jpg",
    title: "Cheese Burger",
    price: 300,
    rating: 4.8,
    category: "Burgers",
  },
  {
    image: "/images/burger3.jpg",
    title: "Double Cheese Slice",
    price: 150,
    rating: 4.8,
    category: "Burgers",
  },
  {
    image: "/images/noodles.jpg",
    title: "Plain Fries",
    price: 130,
    rating: 4.8,
    category: "Fries",
  },

  {
    image: "/images/noodles.jpg",
    title: "Cheese Fries",
    price: 200,
    rating: 4.8,
    category: "Fries",
  },
  {
    image: "/images/noodles.jpg",
    title: "Peri Peri Fries",
    price: 150,
    rating: 4.8,
    category: "Fries",
  },
  {
    image: "/images/noodles.jpg",
    title: "Plain Wedges",
    price: 200,
    rating: 4.8,
    category: "Wedges",
  },
  {
    image: "/images/noodles.jpg",
    title: "Peri Peri Wedges",
    price: 250,
    rating: 4.8,
    category: "Wedges",
  },

  {
    image: "/images/noodles.jpg",
    title: "Cheese Wedges",
    price: 300,
    rating: 4.8,
    category: "Wedges",
  },
  {
    image: "/images/dosa.jpg",
    title: "Plain Dosa",
    price: 100,
    rating: 4.8,
    category: "Dosa",
  },
  {
    image: "/images/paneer.jpeg",
    title: "Masala Dosa",
    price: 130,
    rating: 4.8,
    category: "Dosa",
  },
  {
    image: "/images/dosa.jpg",
    title: "Schezwan Dosa",
    price: 170,
    rating: 4.8,
    category: "Dosa",
  },
  {
    image: "/images/paneer.jpeg",
    title: "Paneer Dosa",
    price: 200,
    rating: 4.8,
    category: "Dosa",
  },
  {
    image: "/images/noodles.jpg",
    title: "Manchow Soup",
    price: 150,
    rating: 4.8,
    category: "Soup",
  },
  {
    image: "/images/noodles.jpg",
    title: "Hot & Sour Soup",
    price: 150,
    rating: 4.8,
    category: "Soup",
  },
  {
    image: "/images/noodles.jpg",
    title: "Lemon Coriander Soup",
    price: 170,
    rating: 4.8,
    category: "Soup",
  },
  {
    image: "/images/noodles.jpg",
    title: "Rajma Rice",
    price: 150,
    rating: 4.8,
    category: "Rice",
  },
  {
    image: "/images/noodles.jpg",
    title: "Sambhar Rice",
    price: 150,
    rating: 4.8,
    category: "Rice",
  },
  {
    image: "/images/noodles.jpg",
    title: "Channa Rice",
    price: 150,
    rating: 4.8,
    category: "Rice",
  },
  {
    image: "/images/noodles.jpg",
    title: "Tawa Roti",
    price: 150,
    rating: 4.8,
    category: "Roti",
  },
  {
    image: "/images/masala tea.jpeg",
    title: "Masala Tea",
    price: 50,
    rating: 4.8,
    category: "Beverages",
  },
  {
    image: "/images/lassi.webp",
    title: "Lassi",
    price: 80,
    rating: 4.8,
    category: "Beverages",
  },
  {
    image: "/images/water3.jpg",
    title: "Water",
    price: 30,
    rating: 4.8,
    category: "Beverages",
  },
  {
    image: "/images/cold drink.jpg",
    title: "Cold Drink",
    price: 50,
    rating: 4.8,
    category: "Beverages",
  },
  {
    image: "/images/mojito.jpg",
    title: "Mojitos",
    price: 150,
    rating: 4.8,
    category: "Beverages",
  },
];

export const categories = [
  { name: "All", icon: "/images/momo2.jpg" },
  { name: "Noodles", icon: "/images/momo2.jpg" },
  { name: "Burgers", icon: "/images/momo2.jpg" },
  { name: "Fries", icon: "/images/momo2.jpg" },
  { name: "Wedges", icon: "/images/momo2.jpg" },
  { name: "Momos", icon: "/images/momo2.jpg" },
  { name: "Dosa", icon: "/images/momo2.jpg" },
  { name: "Soup", icon: "/images/momo2.jpg" },
  { name: "Chinese", icon: "/images/momo2.jpg" },
  { name: "Rice", icon: "/images/momo2.jpg" },
  { name: "Roti", icon: "/images/momo2.jpg" },
  { name: "Beverages", icon: "/images/momo2.jpg" },
];
